import { writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { schema } from '../schema.ts';

/**
 * 由 schema 生成 RLS 迁移。
 *   npx tsx src/scripts/generate-rls.ts                 # 全部表 → db/migrations/0002_rls.sql
 *   npx tsx src/scripts/generate-rls.ts --table <name>  # 单表 → db/migrations/00MM_rls_<name>.sql（自动编号）
 */
const here = dirname(fileURLToPath(import.meta.url));
const dir = resolve(here, '../../../db/migrations');

const header = `-- AUTO-GENERATED by @rls-kit/core from api/src/schema.ts
-- 勿手改；重生成：npx tsx src/scripts/generate-rls.ts${process.argv.includes('--table') ? ' --table <name>' : ''}
-- =============================================================

`;

const args = process.argv.slice(2);
const ti = args.indexOf('--table');
const table = ti >= 0 ? args[ti + 1] : null;

const all = schema.toRlsStatements();

if (table) {
  const isFn = (s: string) => s.includes('create or replace function');
  const forTable = (s: string) =>
    new RegExp(`\\btable public\\.${table}\\b`).test(s) ||
    new RegExp(`\\bpolicy ${table}_`).test(s);
  const stmts = all.filter((s) => isFn(s) || forTable(s));

  const nums = readdirSync(dir)
    .map((f) => /^(\d{4})_/.exec(f)?.[1])
    .filter(Boolean)
    .map((n) => Number(n));
  const next = String(Math.max(0, ...nums) + 1).padStart(4, '0');
  const out = resolve(dir, `${next}_rls_${table}.sql`);
  writeFileSync(out, header + stmts.join('\n\n') + '\n', 'utf8');
  process.stdout.write(`wrote ${out} (${stmts.length} statements)\n`);
} else {
  const out = resolve(dir, '0002_rls.sql');
  writeFileSync(out, header + all.join('\n\n') + '\n', 'utf8');
  process.stdout.write(`wrote ${out}\n`);
}
