-- AUTO-GENERATED by @rls-kit/core from api/src/schema.ts
-- 勿手改；重生成：npx tsx src/scripts/generate-rls.ts
-- =============================================================

create or replace function public.rls_tenant_id() returns uuid
language sql stable as $$ select nullif(current_setting('app.tenant_id', true), '')::uuid $$;

create or replace function public.rls_uid() returns uuid
language sql stable as $$ select nullif(current_setting('app.user_id', true), '')::uuid $$;

create or replace function public.rls_role() returns text
language sql stable as $$ select nullif(current_setting('app.role_type', true), '') $$;

create or replace function public.rls_is_admin() returns boolean
language sql stable as $$ select current_setting('app.role_type', true) = 'tenant_admin' $$;

alter table public.tenant enable row level security;

create policy tenant_select on public.tenant
  for select using (id = public.rls_tenant_id());

create policy tenant_insert on public.tenant
  for insert with check (id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'));

create policy tenant_update on public.tenant
  for update using (id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'))
  with check (id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'));

create policy tenant_delete on public.tenant
  for delete using (id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'));

alter table public.app_user enable row level security;

create policy app_user_select on public.app_user
  for select using (tenant_id = public.rls_tenant_id());

create policy app_user_insert on public.app_user
  for insert with check (tenant_id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'));

create policy app_user_update on public.app_user
  for update using (tenant_id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'))
  with check (tenant_id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'));

create policy app_user_delete on public.app_user
  for delete using (tenant_id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'));

alter table public.operation_log enable row level security;

create policy operation_log_select on public.operation_log
  for select using (tenant_id = public.rls_tenant_id() and (public.rls_role() in ('tenant_admin') or (public.rls_role() = 'member' and operate_user_id = public.rls_uid())));

create policy operation_log_insert on public.operation_log
  for insert with check (tenant_id = public.rls_tenant_id());

alter table public.demo_item enable row level security;

create policy demo_item_select on public.demo_item
  for select using (tenant_id = public.rls_tenant_id());

create policy demo_item_insert on public.demo_item
  for insert with check (tenant_id = public.rls_tenant_id() and (public.rls_role() in ('tenant_admin') or (public.rls_role() = 'member' and owner_id = public.rls_uid())));

create policy demo_item_update on public.demo_item
  for update using (tenant_id = public.rls_tenant_id() and (public.rls_role() in ('tenant_admin') or (public.rls_role() = 'member' and owner_id = public.rls_uid())))
  with check (tenant_id = public.rls_tenant_id() and (public.rls_role() in ('tenant_admin') or (public.rls_role() = 'member' and owner_id = public.rls_uid())));

create policy demo_item_delete on public.demo_item
  for delete using (tenant_id = public.rls_tenant_id() and public.rls_role() in ('tenant_admin'));
